on:
  push:
    tags:
      - "v*"
jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get wails
        run: go get -u github.com/wailsapp/wails/cmd/wails@v1.0.2
      - name: Build package MacOS
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          echo "building on ${{ matrix.os }}"
          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          wails build -p
          ls
          echo "turning the .app into a .dmg"
          npm install -g appdmg
          appdmg dmg-spec.json WailsTodo.dmg
        if: matrix.os == 'macos-latest'
      - name: Build package Linux
        run: |
          sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          export PATH=${PATH}:`go env GOPATH`/bin
          echo "building on ${{ matrix.os }}"
          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          wails build
          # turn into app image
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          ls ./
          ./linuxdeploy*.AppImage --appdir AppDir --executable WailsTodo --desktop-file=WailsTodo.AppImage.desktop --icon-file=appicon.png --output appimage
        if: matrix.os == 'ubuntu-latest'
      - name: Build package Windows
        run: |
          $GP = (go env GOPATH)
          $env:path = "$env:path;$GP\bin"
          echo "building on ${{ matrix.os }}"
          New-Item -ItemType directory -Path "$HOME\.wails" -Force
          Copy-Item -Path "$PWD\wails.json" -Destination "$HOME\.wails\wails.json"
          choco install mingw
          wails build -p
        if: matrix.os == 'windows-latest'

  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "WailsTodo.dmg,WailsTodo.exe,WailsTodo*.AppImage"
